### ISSUE TITLE
Vídeo: reglas de seguridad en Firebase

### ISSUE THREAD

**Issue by kcmr** [UlisesGascon/curso-js-web-developers-112015#11]
Dejo por aquí un link a un vídeo que me ha aclarado algunas cosas sobre las security rules en FB: https://www.youtube.com/watch?v=3NC9yBsSwrs&list=PLTgRMOcmRb3PJ9BdT8g5Wr9BXpRF0d2Zb&index=5

Aunque mi "app" sigue teniendo una seguridad de m$@#!a... :)

La lista de reproducción entera: https://www.youtube.com/playlist?list=PLTgRMOcmRb3PJ9BdT8g5Wr9BXpRF0d2Zb

**Comment by xDae** [comment]
mola,
gracias! :smile_cat:

**Comment by UlisesGascon** [comment]
genial, gran recurso! :+1: 

Recordad que además de la seguridad desde ese archivo se pueden gestionar [la validación de datos](https://www.firebase.com/docs/security/guide/securing-data.html#section-validate) y [la indexación](https://www.firebase.com/docs/security/guide/indexing-data.html#section-indexing-order-by-child). Firebase te avisa cuando es necesario realizar un ajuste en la indexación
