### ISSUE TITLE
Pasar objeto ejercicio movieFire

### ISSUE THREAD

**Issue by tritio** [UlisesGascon/curso-js-web-developers-112015#13]
Hola,

en el ejercicio movieFire, he modificado algunas cosas, y en la función genLinks en lugar de pasarle solo dos propiedades le paso el objeto completo. Me funciona bien, pues hago lo siguiente y compruebo que obtengo el objeto en la función genLinks, pero al pasarlo por la función edit y del, creo que pierdo ahí el objeto y no tengo muy claro por qué: 

function genLinks(laLista) {
    console.log(laLista);  // devuelve correctamente el objeto
    var links = '';

```
  links += '<a href="javascript:edit(\'' + laLista + '\')">Editar</a>';
links += '<a href="javascript:del(\'' + laLista + '\')">Borrar</a>';


return links;
```

};

function edit(laLista) {
    console.log(laLista);  // imprime:  [object Object]
    var movieName = prompt("Update the movie name", laLista.title); // to keep things simple and old skool :D
    if (movieName && movieName.length > 0) {
        // build the FB endpoint to the item in movies collection
        var updateMovieRef = buildEndPoint(laLista.key);
        updateMovieRef.update({
            title: movieName
        });
    }
} 

gracias

**Comment by UlisesGascon** [comment]
Hola! Creo que la clave del problema esta en como se almacena _laLista_ cuando se incluye en el html. En este caso es interesante seguir usando dos parámetros o cambiar del todo la lógica usando eventos y atributos de los elementos. En estas próximas clases veremos como enfrentarnos a este tipo de problemas con herramientas nuevas. ;-)
