### ISSUE TITLE
Patrones de diseño

### ISSUE THREAD

**Issue by xDae** [UlisesGascon/curso-js-web-developers-112015#15]
Aqui os dejo un articulo sobre patrones de diseño en javascript, extendiendo un poco lo que se vio en clase

https://scotch.io/bar-talk/4-javascript-design-patterns-you-should-know

**Comment by UlisesGascon** [comment]
Gracias @xDae  ! Gran aportación :+1: 

Aun nos quedan algunos patrones avanzados por ver en la clase de mañana (Iterator, Façade, Mediator, Mixins... )

Os paso un libro de [Addy Osmani sobre Patrones](http://addyosmani.com/resources/essentialjsdesignpatterns/book/) que es muy completo.
