### ISSUE TITLE
Fin del curso

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/curso-js-web-developers-112015#18]
Hola a todos!

He reorganizado un poco todo en el repositorio y he subido las últimas soluciones. También he modificado un poco el [README.md](https://github.com/UlisesGascon/curso-js-web-developers-112015/blob/master/README.md) para que podáis ir a las practicas directamente sin tener que pasar por todo el temario.

En estos días subiré a GitHub lo que vimos en la última clase con [Arduino](https://www.arduino.cc/), [Edubasica](http://www.practicasconarduino.com/edubasica/), Nodejs, [Johnny-five](http://johnny-five.io/) y [WebSockets](https://www.wikiwand.com/es/WebSocket)
![Foto](https://raw.githubusercontent.com/UlisesGascon/curso-js-web-developers-112015/master/otros/edubasica_shield_hardware.png)

En cuanto a los proyectos personales... recordad que en principio no hay ningún limite de tiempo. Así que podemos verlo tranquilamente en las próximas semanas/meses. Si alguien necesita ayuda para buscar una idea sobre la que trabajar o se atasca en algún punto... no dudéis en contactarme! 

**Importante! Realizar un Fork del repositorio.. ahora que ya esta cerrado!**

Os paso los links a mis redes sociales para que sigamos en contacto!
- [Linkedin](https://es.linkedin.com/in/ulisesgascon)
- [Twitter](https://twitter.com/kom_256)

Felices fiestas y espero vernos pronto con los proyectos personales!

**Comment by kcmr** [comment]
Parece evidente, pero... ¿hemos terminado el curso? Tenía entendido que acababa en enero... Mi proyecto personal tiene bastante trabajo por delante todavía pero estoy en ello :)
