### ISSUE TITLE
Proyecto

### ISSUE THREAD

**Issue by xDae** [UlisesGascon/curso-js-web-developers-112015#20]
Bueno, este finde he estado entretenido haciendo el ejercicio de las películas a mi manera
En este caso en vez de hacerlo con backbone, he preferido probar con [Vue](https://github.com/vuejs/vue), que me pareció un proyecto bastante interesante (mezclando filosofías de algunos de los frameworks mas famosos)

No es mas que un agregador de peliculas que tira de dos apis (tmdb y fanart.tv) y con firebase como (no)backend.

Si tengo tiempo, me gustaría añadirle un login/localstorage para poder separar las peliculas que mas te gusten o algo asi (aun no lo se muy bien jeje)

aquí tenéis el enlace del proyecto en Github, feel free to contribute!
https://github.com/xDae/vue-fireMovie

Un saludo!

**Comment by UlisesGascon** [comment]
Hola @xDae! WOOW! Esta genial, me gusta mucho que te lanzaras con Vue!

He visto alguna cosita que puede mejorarse sobretodo con imágenes y textos cuando el API no devuelve los datos esperados... o cuando los textos de la sinopsis son muy largos y se cortan visualmente. Te paso los issues via repositorio ;-)

Ya estoy pensando en un par de pull-request para enviar! 

Un abrazo!!

**Comment by xDae** [comment]
Lo de los textos ya me di cuenta, esperaba hacer algo en css para cortar antes de que se pegue todo abajo, o quizas agregar un scroll interno al modal.

en cuanto a los datos de la API, no sabia muy bien como proceder, pero investigaré algo
