### ISSUE TITLE
aplicacliones nobackend con AWS :question:

### ISSUE THREAD

**Issue by xDae** [UlisesGascon/curso-js-web-developers-112015#8]
Relacionado con el tema de crear aplicaciones web sin necesidad de backend, encontre hace un tiempo un proyecto para crear aplicaciones usando amazon web services y nodejs

https://github.com/jaws-framework/JAWS

he estado mirando un poco de documentacion al respecto, y parece un proyecto interesante, alguna idea sobre él?

http://docs.aws.amazon.com/es_es/lambda/latest/dg/welcome.html

**Comment by UlisesGascon** [comment]
Hoy veremos Firebase y hablaremos mucho sobre vivir sin back... aun así existen multitud de opciones y arquitecturas alternativas. Hablaremos de ello hoy en clase ;-)

**Comment by tritio** [comment]
Hola,
no sé si es aquí donde hacer la consulta, pero estoy con el ejercicio de Firebase y no me queda muy claro como obtener los datos (nombre, email..) para poder pintarlos en el html. Intento recorrerlo pero no sé muy bien cómo hacerlo: 

 var ref = new Firebase("https://eventogonza.firebaseio.com/fiesta");
          var usuariosRef = ref.child("usuarios");
          usuariosRef.on('value', function(elDato){
                var datosCompletos = elDato.val();
                var dibujar;

¿cómo recorro usuariosRef para obtener cada uno de los registros? Utilizando .length no me sale

Gracias,

**Comment by UlisesGascon** [comment]
Hola @tritio !

_.val()_ te devuelve un _objeto_ por cada _child_. Estos objetos tienen la misma estructura que en la base de datos. [Más info](https://www.firebase.com/docs/web/api/datasnapshot/val.html)

``` javascript
Object {
Apellidos: "asdfa", 
Email: "gonza@gomez.com", 
Nombre: "pepi"
}
```

He incluido unos pequeños cambios en el código. Para acceder a los datos solo necesitamos manejar el objeto (_datosCompletos.Nombre, datosCompletos.Apellidos, datosCompletos.Email_)

``` javascript
var ref = new Firebase("https://eventogonza.firebaseio.com/fiesta");
var usuariosRef = ref.child("usuarios");
var inscritos = "";

usuariosRef.on("child_added", function(elDato) {
    var datosCompletos = elDato.val();
    inscritos += '<div>'+datosCompletos.Nombre + ' ' + datosCompletos.Apellidos + '(' + datosCompletos.Email + ')</div>';
    document.body.innerHTML = inscritos;
});
```

Mañana lo vemos en detalle en clase  ;-)
